### ISSUE TITLE
Add some screenshots

### ISSUE THREAD

**Issue by arthurlogilab** [sdumetz/aptly-web-ui#4]
First of all : congrats this looks awesome and can maybe ease the adoption of using debian packages is some contexts. 

It would be nice to have some screenshots, some examples below : 

![screenshot_2016-12-01_15-37-07](https://cloud.githubusercontent.com/assets/445200/20797691/33077d76-b7dc-11e6-8cdf-7f818c4eff70.png)
![screenshot_2016-12-01_15-35-33](https://cloud.githubusercontent.com/assets/445200/20797692/330884dc-b7dc-11e6-8767-afa373673b9a.png)

**Comment by sdumetz** [comment]
Thanks. I was thinking of a walkthrough of the app's different screen where those screenshots would be really useful.

I'll see when I can get it done.

**Comment by crazy54** [comment]
From someone that found the project on the googles: If it were not for this thread, I would not have seen what it looks like and possibly passed on the project!  Add some screenshots so you don't lose more traffic like me and get more of us developing this out.  :)

**Comment by sdumetz** [comment]
Added one screenshot to the home page. Will use the other when I add some documentation. Feel free to open a PR to contribute some doc if you'd like to.

Thanks for contributing!
